[package]
name = "cranpose-ui-graphics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Pure math/data for drawing & units in Cranpose"

[dependencies]

[features]
default = []
